In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('item_popularity.csv')
data.head(10)

    item_id  pop_percent
0  it_01345      0.98324
1  it_03431      0.56123
2  it_04572      0.12098
3  it_98021      0.35476
4  it_01298      0.92101
5  it_90120      0.81212
6  it_10123      0.56502

In [4]:
data['pop_scale_10'] = np.array(np.round((data['pop_percent']*10)),dtype='int')
data['pop_scale_100'] = np.array(np.round((data['pop_percent']*100)),dtype='int')
data.head(10)

    item_id  pop_percent  pop_scale_10  pop_scale_100
0  it_01345      0.98324            10             98
1  it_03431      0.56123             6             56
2  it_04572      0.12098             1             12
3  it_98021      0.35476             4             35
4  it_01298      0.92101             9             92
5  it_90120      0.81212             8             81
6  it_10123      0.56502             6             57